### ISSUE TITLE
Reference to HATS

### ISSUE THREAD

**Issue by cmpadden** [ECE4574-5574/devices_t2#20]
I am unable to build master with an unresolved reference to HATS.

**Comment by jasedit** [comment]
How are you building it? It will only build through the Automation_System repository (which is specifically designed to integrate everything together.)

Assuming you are, what's the exact build error?

**Comment by ibalajiarun** [comment]
No. We are building it separately. We could not integrate with the Automation_System repo, because we could not understand git submodules. Where is HATS described. If you specify the project, I will work towards pulling it to our solution.

**Comment by ibalajiarun** [comment]
Is it in Sim Harness? I think I found it

**Comment by jasedit** [comment]
The error is likely Hats.Time, which is in the sim_harness repository. You’re going to have a hell of a time integrating without using the repo - the entire point of the repo is to allow people to share their integration efforts, as opposed to fighting all these issues.

Jason

**Comment by cmpadden** [comment]
I agree that we should put our efforts into integrating the MobileApp repository into Automation_System.

**Comment by aakruthigopisetty** [comment]
Yes! We should somehow get everything within this repo for everything to
run smoothly.
