### ISSUE TITLE
Changes required in enumerateDevices function

### ISSUE THREAD

**Issue by arunkt1** [ECE4574-5574/devices_t2#27]
public List<string> enumerateDevices(Uri address) in DeviceAPI.cs should take in houseID as one of its inputs in order for the app to query the new devices in a particular house which are not yet registered. The return value could be a JSON blob which includes deviceID, devicetype and houseID.

**Comment by jasedit** [comment]
DeviceID won't exist yet, as the devices aren't registered, and DeviceID is something that is a post-condition of the register call. However, it should have a type and House ID. This is in progress.
