### ISSUE TITLE
ServerInput class not implemented

### ISSUE THREAD

**Issue by jasedit** [ECE4574-5574/devices_t2#35]
This class implements the communication from the app to the server in requesting state updates for a device. This particular class is instantiated inside for the Device instances residing in the app or Decision Making parts of the system, as their method for reading data from the server about the device.

**Comment by nandadong** [comment]
Hi Jason,

Does the configuration of the ServerInput/ServerOutput instances have
something to do with the internal parameters(if needed) in the classes(say,
the constructor of Server I/O stores some value from the input)? And then
we modify the Device instance by the values from that instantiation?

Thank you,
Dong

2015-04-20 1:42 GMT-04:00 Jason Ziglar notifications@github.com:

**Comment by jasedit** [comment]
ServerInput and output should be configured based on some external parameters (namely, the URL for the server), but shouldn’t have any explicit parameters from the Device object that I’m aware of. During the read/write call it may use parameters available in the Device to perform the update, but it won’t be storing copies of those values.

Jason

**Comment by nandadong** [comment]
Jason, here's the structure of the ServerInput:

public class ServerInput : IDeviceInput
{
public ServerInput()
{
}

/**
- Updates device from the server
  _/
  public bool read(Device dev)
  {
  //TODO: Implement this function
             \* //Question: Should I simply call "dev.update();" here and
  get the "update()" function implemented in Device.cs or how can I get "dev"
  updated here                               //in ServerInput?_
  return true;
  }
  }

Thank you,
Dong

2015-04-20 16:06 GMT-04:00 Jason Ziglar notifications@github.com:

> ServerInput and output should be configured based on some external
> parameters (namely, the URL for the server), but shouldn’t have any
> explicit parameters from the Device object that I’m aware of. During the
> read/write call it may use parameters available in the Device to perform
> the update, but it won’t be storing copies of those values.
> 
> Jason
>

**Comment by jasedit** [comment]
No - dev.update will be calling ServerInput, not the other way around. The read function should be making the calls to the Server API to get the latest state of the device, and inserting those values into dev. You can likely use Interfaces.UpdateDevice to do the vast majority of this work - you simply need to make the ServerAPI call to get device state.

**Comment by nandadong** [comment]
Currently it seems no such api from Server API for us to call for device
state.

**Comment by nandadong** [comment]
Hey Jason,

Do we call "public HttpResponseMessage Get(int id)" in
"House/Controllers/DeviceController" to make the call to ServerAPI to
request the device state? If yes, how do I convert the HttpResponseMessage
type to a json string to input in the Interfaces.UpdateDevice?

Thank you,
Dong

2015-04-20 21:52 GMT-04:00 nandong南东 raitodong@gmail.com:

> Currently it seems no such api from Server API for us to call for device
> state.
>

**Comment by jasedit** [comment]
Closed as of #76.
