### ISSUE TITLE
Device classes need to be plumbed to correctly use IDevice(Input|Output)

### ISSUE THREAD

**Issue by jasedit** [ECE4574-5574/devices_t2#39]
This means ensuring that all properties of the devices use the relevant member variables to get/set state, as well as making sure that when devices are instantiated, the correct input/output objects are created.

**Comment by willrd9** [comment]
Okay great I'll do that today and have the test methods created as well

**Comment by willrd9** [comment]
Should the setter of  ID in devices be expecting a FullID object or should I create multiple methods for setting HouseID, RoomID, and DeviceID individually, or include functionality for both?

**Comment by jasedit** [comment]
You can access the subfields by simply doing “device.ID.HouseID” - so no need to modify that.

**Comment by willrd9** [comment]
Okay

**Comment by willrd9** [comment]
All of my nuget packages are installed but cannot be found under references thus causing build errors. Any ideas? I can test after I work that out

![capture](https://cloud.githubusercontent.com/assets/7495643/7233406/191a1f0e-e74f-11e4-939c-fd041e9d8b05.PNG)

**Comment by jasedit** [comment]
Are you checking out from the Automation_System repository? Do you have local mods to that repository which are changing the Reference locations? What version/status is the repository?

**Comment by willrd9** [comment]
Sorry I was in class. And I am not using the Automation_System repository. Just simply trying to build the Device repo. I have no local mods which change the Reference location. I did a fresh restore of all nuget packages so they are all there in the packeges folder in the sln root but the references cannot seem to find them. The repo is at the most current version.

**Comment by jasedit** [comment]
You will be unable to build the Device repo without using the Automation_System repository without major reworking of the repository, to the point that it no longer builds with any other part of the system. You need to use Automation_System to build the system - there’s just no way around it any longer.

Jason

**Comment by willrd9** [comment]
Okay. Well I tried that and apparently that requires a different version of VS. So I'll try to get that reworked.

**Comment by jasedit** [comment]
What requires a different version a VisualStudio? The difference in repositories shouldn’t affect VisualStudio in any significant fashion.

**Comment by willrd9** [comment]
Okay the problem was on my end! Thanks @jasedit

**Comment by jasedit** [comment]
Implemented as of #63.
