### ISSUE TITLE
Implement enumerateDevice() function and logic

### ISSUE THREAD

**Issue by arunkt1** [ECE4574-5574/devices_t2#52]

**Comment by jasedit** [comment]
Which modifications are being proposed in this Issue which are not covered in #40? If you and @sscho91 are splitting up the work in DeviceAPI, I'm completely on board with that - I just want to make sure that it is explicit what each of you are doing, so there's no confusion or duplicated effort.

You might split up the functions (e.g. one of you handles the `getDevices()` calls, the other handles enumerate/register/delete.) One of you might want to look into what functions, if any, are missing from the point-of-view of ServerAPI, MobileApp, or Decision Making. You may want to split between looking at the REST API calls vs. parsing the results - any of those might work, just as long as you guys agree and can integrate your work.

**Comment by arunkt1** [comment]
I got you Jason. I will send an email to him right away. Could you include
me in a group email so that I could get the email addresses of all our team
members?

Thanks
Arun

**Comment by arunkt1** [comment]
Sure, we will work out a plan to split it.

**Comment by jasedit** [comment]
From the class wiki list, this issue covers:
1. Implement enumerateDevice() function for app usage. Note that this requires not only getting the list of devices from the house, but also determining where/how the list of devices is filtered for devices which are already registered. The house is not aware of which devices are registered - this information should be stored in persistent storage. It seems like this is ServerAPI, but it should be made explicit.
2. Verify that the ServerAPI for enumerateDevices() exists/will be created.

**Comment by jasedit** [comment]
Closed as of #75.
